import { PERMISSION_KEYS } from "../permissions/permission.catalog.js";
import type { SystemRoleSlug } from "./role.model.js";

/**
 * Default permission grants for the 4 built-in roles — matches exactly what the previous
 * hardcoded-enum RBAC allowed, so migrating to dynamic roles changes no actual authorization
 * outcome for the default setup. Organizers can edit their own copy of these afterward.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRoleSlug, string[]> = {
  SUPER_ADMIN: [...PERMISSION_KEYS],
  ORGANIZER: [
    "chit_group.create",
    "chit_group.view",
    "chit_group.update",
    "chit_group.enroll_member",
    "chit_group.activate",
    "users.create_member",
    "users.create_staff",
    "users.view",
    "users.approve",
    "activity_log.view_tenant",
    "organization.manage",
    "branch.manage",
    "subscription.view",
    "role.manage",
    "upload.create",
    "members.create",
    "members.view",
    "members.update",
    "members.delete",
    "members.verify_kyc",
    "members.import_export",
    "collection.record",
    "collection.view",
    "collection.manage_dues",
    "auction.view",
    "auction.record_bid",
    "auction.manage",
    "payout.view",
    "payout.disburse",
    "report.view",
    "report.export",
    "report.manage_finance",
    "notification.view",
    "notification.send",
    "notification.manage_templates",
    "dashboard.view",
  ],
  STAFF: [
    "chit_group.create",
    "chit_group.view",
    "chit_group.update",
    "chit_group.enroll_member",
    "chit_group.activate",
    "users.create_member",
    "users.view",
    "activity_log.view_tenant",
    "upload.create",
    "members.create",
    "members.view",
    "members.update",
    "collection.record",
    "collection.view",
    "collection.manage_dues",
    "auction.view",
    "auction.record_bid",
    "auction.manage",
    "payout.view",
    "payout.disburse",
    "report.view",
    "report.export",
    "notification.view",
    "notification.send",
    "dashboard.view",
  ],
  MEMBER: ["upload.create", "dashboard.view", "chit_group.view", "auction.view", "collection.view", "notification.view"],
};

export const DEFAULT_ROLE_LABELS: Record<SystemRoleSlug, string> = {
  SUPER_ADMIN: "Super Admin",
  ORGANIZER: "Organizer",
  STAFF: "Staff",
  MEMBER: "Member",
};
